### ISSUE TITLE
Can't install via 'npm install favicons' on Debian 8

### ISSUE THREAD

**Issue by adams-family** [itgalaxy/favicons#285]

**Comment by adams-family** [comment]
Maybe it's caused by my stupidity :-) then sorry about that but I can't seem to install this package via 'npm install favicons' because of the following error:

```
> npm install favicons --save

> sharp@0.22.1 install /var/www/projects/favicon-generator/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /root/.npm/_libvips/libvips-8.7.4-linux-x64.tar.gz
ERR! sharp zlib: zlib binding closed
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/page/install for required dependencies
make: Entering directory '/var/www/projects/favicon-generator/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:25:22: fatal error: vips/vips8: No such file or directory
 #include <vips/vips8>
                      ^
compilation terminated.
sharp.target.mk:115: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: *** [Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/var/www/projects/favicon-generator/node_modules/sharp/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/projects/favicon-generator/node_modules/sharp
gyp ERR! node -v v6.1.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN favicon-generator@1.0.0 No description
npm WARN favicon-generator@1.0.0 No repository field.
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "favicons" "--save"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.22.1 install script '(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/projects/favicon-generator/npm-debug.log
```

**Node version:**
v6.1.0

**NPM version:**
3.8.6

**Debian version:**
Debian GNU/Linux 8

Any clue much appreciated, otherwise I guess I'll upgrade my environment and retry.

**Comment by adams-family** [comment]
Sorry guys, after gathering all data about my issue I found that this is because I have to update my NodeJS environment:

https://stackoverflow.com/questions/53022392/installing-sharp-usr-include-vips-vips83525-fatal-error-glib-object-h

I think you can close this issue in this case :)

**Comment by dockleryxk** [comment]
@adams-family will you explain what you did? I am getting this error on macos and Ubuntu:

```
info sharp Using cached /Users/tommy/.npm/_libvips/libvips-8.8.1-darwin-x64.tar.gz
prebuild-install WARN install dlopen(/Users/tommy/dev/src/storagepug/rhs/node_modules/sharp/build/Release/sharp.node, 1): Library not loaded: @rpath/libvips-cpp.42.dylib
prebuild-install WARN install   Referenced from: /Users/tommy/dev/src/storagepug/rhs/node_modules/sharp/build/Release/sharp.node
prebuild-install WARN install   Reason: image not found
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:25:10: fatal error: 'vips/vips8' file not found
#include <vips/vips8>
         ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/tommy/dev/src/storagepug/rhs/node_modules/sharp
gyp ERR! node -v v10.16.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.23.0 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.23.0 install script.
```

**Comment by adams-family** [comment]
Sure, I got the error on NodeJS v6.1.0. I learned on stackoverflow that this version of NodeJS is not supported by one of the components.

I tried my luck on Docker with NodeJS 10.8.0 and that solved my problem.

I can describe what I did (I hope I haven't forgot for anything):

Dockerfile:
```
FROM node:10.8.0
WORKDIR /usr/src/app
RUN npm install nodemon -g
CMD [ "nodemon", "index.js" ]
```

docker-compose.yml:
```
version: "3.7"

services:
  node:
    build: .
    volumes:
      - ./src:/usr/src/app
      - ./data:/usr/src/data
    environment:
      - "INPUT=/usr/src/data/source.png"
      - "OUTPUT=/usr/src/data/output"
```

Created a **data** folder where I put `source.png`.

Created a **src** folder where I put:
  - index.js - with the example from this github repository (just changed the source file name to source.png)
  - package.json:
```
{
  "name": "server",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "nodemon index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "favicons": "^5.4.1"
  }
}
```

Then I run:
- `docker-compose up` - in one terminal
- while the above command was running: `docker-compose exec node npm install` - to install npm dependencies

Aftern npm install has finished, nodemon automatically restarted my script and favicon generation works :)

**Comment by dockleryxk** [comment]
@adams-family thank you! It turns out my issue is related to this: https://github.com/lovell/sharp/issues/1882
