### ISSUE TITLE
Update npm-Package

### ISSUE THREAD

**Issue by juliantroeps** [itgalaxy/favicons#292]
Shouldn't we update the npm package to 5.0.0 (currently 5.4.1) and put the latest version under Releases? Additionally we could use the GitHub Packages feature.

**Comment by evilebottnawi** [comment]
Do you want new release?

**Comment by buzz** [comment]
I'd very much like to see a new release.

Right now I can't install favicons anymore as sharp-0.22.1 fails to build (npm build log below).
I checked and sharp-0.23.3 builds fine which is already in master.

```
$ npm install favicons

> sharp@0.22.1 install /tmp/personal-tmp/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/user/.npm/_libvips/libvips-8.7.4-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=13.2.0 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/tmp/personal-tmp/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
../src/stats.cc: In member function ‘virtual void StatsWorker::HandleOKCallback()’:
../src/stats.cc:130:37: error: no matching function for call to ‘v8::Array::Set(int&, v8::Local<v8::Object>&)’
         channels->Set(i, channelStat);
                                     ^
In file included from /home/user/.cache/xdgcache/node-gyp/13.2.0/include/node/node.h:63:0,
                 from ../src/stats.cc:19:
/home/user/.cache/xdgcache/node-gyp/13.2.0/include/node/v8.h:3547:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Valu
e>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/user/.cache/xdgcache/node-gyp/13.2.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/home/user/.cache/xdgcache/node-gyp/13.2.0/include/node/v8.h:3550:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Loca
l<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/user/.cache/xdgcache/node-gyp/13.2.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
make: *** [sharp.target.mk:136: Release/obj.target/sharp/src/stats.o] Error 1
make: Leaving directory '/tmp/personal-tmp/node_modules/sharp/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.nvm/versions/node/v13.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! System Linux 5.2.14-2.g7f85414-default
gyp ERR! command "/home/user/.nvm/versions/node/v13.2.0/bin/node" "/home/user/.nvm/versions/node/v13.2.0/lib/node_modules/npm/
node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/personal-tmp/node_modules/sharp
gyp ERR! node -v v13.2.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by evilebottnawi** [comment]
WIP

**Comment by evilebottnawi** [comment]
Done in `5.5.0`
